# Generated by Django 3.2.9 on 2021-11-14 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.IntegerField()),
                ('montant', models.DecimalField(decimal_places=5, max_digits=20)),
                ('date', models.DateField(auto_now_add=True)),
                ('operation', models.CharField(max_length=300)),
                ('commision', models.IntegerField()),
                ('portfeuille', models.DecimalField(decimal_places=4, max_digits=30)),
            ],
        ),
    ]
