# Generated by Django 3.2.9 on 2021-11-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dete', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dete',
            name='credit',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
        migrations.AlterField(
            model_name='dete',
            name='debit',
            field=models.DecimalField(decimal_places=15, max_digits=30),
        ),
    ]
