# Generated by Django 3.2.9 on 2021-11-17 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Description', models.TextField()),
                ('MotantCharge', models.DecimalField(decimal_places=15, max_digits=20)),
                ('Date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
